# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Components - Test and Release

on:
  push:
  pull_request:
    branches: [master]
    paths:
      - "components/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./development/components
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - name: Format
        run: npm run format

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

  release:
    # Only release on push to master
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./development/components

    # Waits for test job
    needs: [test]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare environment
        uses: actions/setup-node@v1

      - name: Install
        run: npm ci

      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deploy Storybook
        run: npm build-storybook && npm run deploy-storybook
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
